### ISSUE TITLE
URL for Thermal is hardcoded

### ISSUE THREAD

**Issue by ehaligow** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#12]
The URL for Thermal in Chassis (l38 in /src/system_operations.go) is hardcoded. The collection should be retrieved from PSME and the url should be set based on the response.

**Comment by JasonscHuang** [comment]
@ehaligow Thanks for sharing this. We already knew all like issues. All kinds of the same issue will fix in the next version.
