### ISSUE TITLE
ChangeDeviceUserPassword func does not work

### ISSUE THREAD

**Issue by ehaligow** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#13]
PATCH is sent to the wrong URL (it returns Not Found response). The URL used is wrongly created – instead of Id, username is used. The mentioned method searches in this collection the following URL:”/redfish/v1/AccountService/Accounts/root” for root user where “/redfish/v1/AccountService /Accounts/2” 
is assigned to root.

**Comment by jcleung5549** [comment]
DM Mtg (Mar 8) - There is a race condition when the Redfish client GETS the Account list and then performs an Action on the one of the accounts, the account could have been deleted and recreated in the duration between the two HTTP actions.  Do ETags solve this?  Are ETags passed with with an POST Action?  Should ODIM BMC simulate return an Etag per spec?  Submitting issue to redfishforum.com.

**Comment by JasonscHuang** [comment]
Please do not test this version. We will provide the new code. You could test it later.

**Comment by JasonscHuang** [comment]
I already uploaded PR #15. Please see this issue has been fixed or not.

**Comment by ehaligow** [comment]
The issue is resolved.
