### ISSUE TITLE
ChangeDeviceUserPassword task in test.go returns wrong status

### ISSUE THREAD

**Issue by ehaligow** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#14]
After executing test task changeuserpassword we can see on terminal the following:
./dm changeuserpassword  192.168.40.206:8888:069b6b7e-7196-455c-b4d7-ccf09d95502e:root:root1
192.168.40.206:8888 changed
While in logs there is an information, that the task did not work – error status is received.

**Comment by JasonscHuang** [comment]
Please do not test this version. We will provide the new code. You could test it later.

**Comment by JasonscHuang** [comment]
I already uploaded PR #15. Please see this issue has been fixed or not.

**Comment by ehaligow** [comment]
The issue is resolved.
