### ISSUE TITLE
Fixes from PR#15 need to be merged in the main branch.

### ISSUE THREAD

**Issue by jcleung5549** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#16]
PR#15 was merged into the redfishapi branch. The changes need to moved to main branch before the issues can be closed.

**Comment by JasonscHuang** [comment]
@jcleung5549 OK. I will do that.

**Comment by JasonscHuang** [comment]
@jcleung5549 I merged branch codes from PR #15 to master.
