### ISSUE TITLE
Hard coded certificate copied into container by Dockerfile could lead to decryption of data by unauthorized network adversary

### ISSUE THREAD

**Issue by huornlmj** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#29]
https://github.com/opencomputeproject/HWMgmt-DeviceMgr-DeviceManager/blob/b68d37cccc7503cef47b0940ad8bcf72f155b69b/device_key/https-server.key#L4

Hi.  There is a hard coded private key here that is copied into the running container in the Dockerfile https://github.com/opencomputeproject/HWMgmt-DeviceMgr-DeviceManager/blob/main/docker/Dockerfile#L27.  If this container is used as-is then a network adversary can sniff the traffic and decrypt the data wherever this is deployed, as the private key is available to anyone who has access to the repo.

This is CWE-321: Use of Hard-coded Cryptographic Key.

**Comment by jcleung5549** [comment]
The intent of the docker files is to more easily deploy the entire virtual topology (Device Manager, SW Agents, etc.) to show how the entire architecture works.  In an actual datacenter, it is expected that the DC will have its own deployment process.
