### ISSUE TITLE
Make all does nothing

### ISSUE THREAD

**Issue by MaciejMis** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#5]
According to these presentations the first step in Device Manager installation is invoking `make all` command. Right now it is not working because it calls `test` target which is nonexistent in Makefile.
- https://drive.google.com/file/d/1ZLk9IjGRsFCsC-smoqDY9ohiCxBavEg9
- https://www.youtube.com/watch?v=zGMIcgPa_LM

Reproduction:
1. `cd` to Device Manager directory
2. `make all`

Output:
`make: *** No rule to make target 'test', needed by 'all'.  Stop.`

**Comment by taskin-ucpinar** [comment]
Edgecore will fix this ASAP.

**Comment by JasonscHuang** [comment]
I already uploaded PR #15. Please see this issue has been fixed or not.

**Comment by MaciejMis** [comment]
> I already uploaded PR #15. Please see this issue has been fixed or not.

Yes, this issue will be resolved once PR will be merged.

**Comment by MaciejMis** [comment]
This issue can be closed.
