### ISSUE TITLE
Feature missing: Firmware Update

### ISSUE THREAD

**Issue by MaciejMis** [opencomputeproject/HWMgmt-DeviceMgr-DeviceManager#7]
According to these presentations Device Manager is capable of Firmware update. Unfortunately this feature is not present in current version of Device Manager.
- https://drive.google.com/file/d/1ZLk9IjGRsFCsC-smoqDY9ohiCxBavEg9
- https://www.youtube.com/watch?v=zGMIcgPa_LM

**Comment by taskin-ucpinar** [comment]
The FW update is a vendor dependent implementation, which will include vendor IP information. So we have left it blank. However, I see OP's point; we should at least pass the request down to the Redfish service on the device.

**Comment by taskin-ucpinar** [comment]
We will modify the Redfish serevice we've contributed to make it return “NotImplemented” by default. Users should reach out to their HW vendors and obtain functional Redfish binaries.

**Comment by JasonscHuang** [comment]
@MaciejMis The software update source code has already in the master branch. You could refer to the software_update.go source code.

**Comment by MaciejMis** [comment]
This issue was fixed in #30
